name: advanced_terminal
description: A starting point for Dart libraries or applications.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.0.2

# Add regular dependencies here.
dependencies:
  ansi_escapes: ^1.1.0
  ansicolor: ^2.0.1
  ansi_styles: ^0.3.2+1
  collection: ^1.18.0


dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
